### ISSUE TITLE
Issue using the redirect

### ISSUE THREAD

**Issue by brionab** [10up/safe-redirect-manager#133] opened 2017-04-19 12:27 UTC
I am working on redirecting to an external URL that is not housed on the server like my current site. When creating the 302 Redirect, I receive the page is not found message. How can I fix this?

**Comment by jayedul** [comment] 2023-01-16 15:19
@jeffpaul 
The issue could not be reproduced. It has been fixed meanwhile as I can see. 
https://user-images.githubusercontent.com/12506700/212711794-313be15f-197e-483e-ab86-ea87d638b786.mov

**Comment by ravinderk** [comment] 2023-07-19 17:36
@jeffpaul Can we close this issue? Because @jayedul  was not able to reproduce this issue as mentioned in [the comment](https://github.com/10up/safe-redirect-manager/issues/133#issuecomment-1384204990).

cc: @dkotter

**Closed** 2023-07-19 18:31 UTC
Labels: type:bug, type:question, help wanted
